apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
        - name: nginx
          image: tashikmoin/nginx-deployment-k8cd:<TAG>
          ports:
            - containerPort: 80
