apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
        - name: nginx
          image: tashikmoin/nginx-deployment-k8cd
          ports:
            - containerPort: 80
